USE [master]
GO

/****** Object:  Database [FİLMLER]    Script Date: 24.01.2021 20:58:00 ******/
CREATE DATABASE [FİLMLER]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FİLMLER', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\FİLMLER.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FİLMLER_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\FİLMLER_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FİLMLER].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FİLMLER] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FİLMLER] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FİLMLER] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FİLMLER] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FİLMLER] SET ARITHABORT OFF 
GO

ALTER DATABASE [FİLMLER] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FİLMLER] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FİLMLER] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FİLMLER] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FİLMLER] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FİLMLER] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FİLMLER] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FİLMLER] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FİLMLER] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FİLMLER] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FİLMLER] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FİLMLER] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FİLMLER] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FİLMLER] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FİLMLER] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FİLMLER] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FİLMLER] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FİLMLER] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FİLMLER] SET  MULTI_USER 
GO

ALTER DATABASE [FİLMLER] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FİLMLER] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FİLMLER] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FİLMLER] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FİLMLER] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FİLMLER] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FİLMLER] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FİLMLER] SET  READ_WRITE 
GO

